name: Test windup e2e
description: Test Windup Addon End-to-End.

inputs:
  host:
    description: Konveyor Host
    default: localhost:8080/hub
  namespace:
    description: Konveyor Namespace
    default: konveyor-tackle

runs:
  using: "composite"
  steps:
  - name: test-e2e
    run: |
      export HOST="${{ inputs.host }}"
      export NAMESPACE="${{ inputs.namespace }}"
      make test-e2e
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
