on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make fmt
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make vet
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make cmd
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make test
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build-image
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: djzager/tackle2-operator/.github/actions/start-minikube@ci-actions
      - name: Build image in minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          make build-image
      - uses: djzager/tackle2-operator/.github/actions/install-tackle@ci-actions
        with:
          tackle-addon-windup-image: tackle2-addon-windup:latest
